export * from "./generated/api";
export * from "./generated/api.schemas";
export { setBaseUrl, setAuthTokenGetter } from "./custom-fetch";
export type { AuthTokenGetter } from "./custom-fetch";

// Consultant API exports
export {
  useGetDashboardStats,
  useGetUpcomingSessions,
  useGetPendingReports,
  useGetWeeklySchedule,
  useGetClientImprovementSummary,
  useGetClients,
  useGetClient,
  useGetClientAssessments,
  useGetClientMood,
  useGetClientHomework,
  useGetClientSessionHistory,
  useSubmitSessionReport,
  useSubmitBlogPost,
  useSubmitBlogOutline,
  useGetCalendarEvents,
  useGetRevenueSummary,
  useGetRevenueAnalytics,
  useGetTransactions,
  useGetReviewsSummary,
  useGetReviews,
  useGetProfile,
  useUpdateProfile,
  useGetCaseloadOutcomes,
} from "./generated/consultant-api";

export type {
  ActivityItem,
  AvailabilityInput,
  AvailabilitySlot,
  BlogOutline,
  BlogOutlineInput,
  BlogPost,
  BlogPostInput,
  CalendarEvent,
  CaseloadOutcomes,
  Client,
  ClientDetail,
  ClientImprovementSummary,
  ClientOutcomes,
  DashboardStats,
  GetCalendarEventsParams,
  GetCaseloadOutcomesParams,
  GetClientsParams,
  GetRevenueAnalyticsParams,
  GetRevenueSummaryParams,
  HomeworkItem,
  MoodTracking,
  PendingReport,
  ProfileUpdate,
  RevenueDataPoint,
  RevenueSummary,
  Review,
  ReviewsSummary,
  SessionHistory,
  SessionReport,
  SessionReportInput,
  TherapistProfile,
  Transaction,
  UpcomingSession,
  WeeklyScheduleDay,
} from "./generated/consultant-api.schemas";
